package com.example.localization

data class AppStrings(
    val appName: String,
    val welcomeTitle: String,
    val welcomeSubtitle: String,
    val username: String,
    val password: String,
    val rememberMe: String,
    val login: String,
    val loggingIn: String,
    val loginError: String,
    val invalidCredentials: String,
    val accountDisabled: String,
    val selectLanguage: String,
    val logout: String,
    val roleAdmin: String,
    val roleTeacher: String,
    val roleStudent: String,
    
    // Navigation
    val navDashboard: String,
    val navUsers: String,
    val navTimetable: String,
    val navFinance: String,
    val navReports: String,
    val navAttendance: String,
    val navResources: String,
    val navHomework: String,
    val navGrades: String,
    val navChat: String,
    val navAnnouncements: String,
    val navSettings: String,
    val navGroups: String,

    // Users
    val usersTitle: String,
    val studentsTab: String,
    val teachersTab: String,
    val addUser: String,
    val addStudent: String,
    val addTeacher: String,
    val fullName: String,
    val phone: String,
    val autoGeneratePassword: String,
    val credentialsTitle: String,
    val credentialsDesc: String,
    val copyCredentials: String,
    val credentialsCopied: String,
    val editUser: String,
    val deleteUser: String,
    val disableUser: String,
    val enableUser: String,
    val confirmDelete: String,
    val teacherPermissions: String,
    val permPublishResources: String,
    val permEditGrades: String,
    val permSendAnnouncements: String,
    val statusActive: String,
    val statusDisabled: String,
    val searchPlaceholder: String,

    // Academic / Timetable
    val groupsTitle: String,
    val subjectsTitle: String,
    val roomsTitle: String,
    val addGroup: String,
    val addSubject: String,
    val addRoom: String,
    val groupName: String,
    val subjectName: String,
    val teacherName: String,
    val roomName: String,
    val manualEntry: String,
    val selectFromList: String,
    val level: String,
    val timetableTitle: String,
    val addSlot: String,
    val dayOfWeek: String,
    val startTime: String,
    val endTime: String,
    val conflictDetected: String,
    val conflictRoom: String,
    val conflictTeacher: String,
    val noConflict: String,
    val weeklySchedule: String,
    val nextClassReminder: String,
    val noScheduleToday: String,

    // Days
    val monday: String,
    val tuesday: String,
    val wednesday: String,
    val thursday: String,
    val friday: String,
    val saturday: String,
    val sunday: String,

    // Attendance
    val attendanceTitle: String,
    val markAttendance: String,
    val present: String,
    val absent: String,
    val late: String,
    val attendanceSaved: String,
    val attendanceRate: String,
    val myAttendanceRecord: String,
    val totalSessions: String,

    // Resources
    val resourcesTitle: String,
    val addResource: String,
    val resourceTitle: String,
    val resourceType: String,
    val typeSummary: String,
    val typeExercise: String,
    val typePastExam: String,
    val fileOrUrl: String,
    val downloadOrOpen: String,

    // Homework
    val homeworkTitle: String,
    val createHomework: String,
    val deadline: String,
    val submissions: String,
    val submitHomework: String,
    val yourSubmission: String,
    val gradeSubmission: String,
    val score: String,
    val teacherComment: String,
    val submittedStatus: String,
    val notSubmittedStatus: String,

    // Grades
    val gradesTitle: String,
    val addGrade: String,
    val gradeType: String,
    val typeExam: String,
    val typeQuiz: String,
    val typeHomeworkGrade: String,
    val gradeValue: String,
    val overallAverage: String,
    val progressChart: String,

    // Finance
    val financeTitle: String,
    val monthlyFees: String,
    val paymentStatus: String,
    val statusPaid: String,
    val statusPending: String,
    val statusOverdue: String,
    val totalCollected: String,
    val totalOverdue: String,
    val recordPayment: String,
    val amount: String,
    val paymentDate: String,

    // Reports
    val reportsTitle: String,
    val attendanceReport: String,
    val gradesReport: String,
    val financeReport: String,
    val exportPdf: String,
    val exportExcel: String,
    val reportExported: String,

    // Announcements
    val announcementsTitle: String,
    val createAnnouncement: String,
    val announcementTitle: String,
    val announcementBody: String,
    val audienceAll: String,
    val audienceTeachers: String,
    val audienceStudents: String,
    val unread: String,

    // Chat
    val chatTitle: String,
    val privateTab: String,
    val groupsTab: String,
    val qaTab: String,
    val newGroupChat: String,
    val recordVoice: String,
    val recording: String,
    val stopAndSend: String,
    val playAudio: String,
    val sendImage: String,
    val typeMessage: String,
    val askQuestion: String,
    val answerQuestion: String,
    val replies: String,
    val moderationNotice: String,
    val deleteMessage: String,

    // Common
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val confirm: String,
    val close: String,
    val copy: String,
    val noDataYet: String,
    val loading: String,
    val success: String,
    val error: String,
    val settingsTitle: String,
    val firebaseStatus: String,
    val connected: String,
    val disconnected: String,
    val setupInstructions: String,
    val securityRulesTitle: String,
    val capacitorStepsTitle: String,
    val initializeAdminButton: String,
    val adminInitializedSuccess: String,

    // Security & Multi-Admin
    val secureAccountTitle: String,
    val secureAccountSubtitle: String,
    val newPassword: String,
    val confirmPassword: String,
    val recoveryEmail: String,
    val changeUsernameOptional: String,
    val passwordCannotBeAdmin: String,
    val passwordsDoNotMatch: String,
    val passwordTooShort: String,
    val invalidEmail: String,
    val saveAndContinue: String,
    val forgotPassword: String,
    val forgotPasswordTitle: String,
    val forgotPasswordDesc: String,
    val sendResetLink: String,
    val resetLinkSent: String,
    val manageAdmins: String,
    val adminsTab: String,
    val addAdmin: String,
    val primaryAdmin: String,
    val you: String,
    val cannotDeletePrimaryAdmin: String,
    val changePassword: String,
    val oldPassword: String,
    val passwordChangedSuccess: String
)

object Translations {
    val Arabic = AppStrings(
        appName = "science.est.center",
        welcomeTitle = "مرحباً بك في science.est.center",
        welcomeSubtitle = "منصة إدارة المدرسة الخاصة ودعم الطلاب المتكاملة",
        username = "اسم المستخدم",
        password = "كلمة المرور",
        rememberMe = "تذكرني",
        login = "تسجيل الدخول",
        loggingIn = "جارٍ تسجيل الدخول...",
        loginError = "خطأ في تسجيل الدخول. تحقق من اسم المستخدم وكلمة المرور.",
        invalidCredentials = "اسم المستخدم أو كلمة المرور غير صحيحة",
        accountDisabled = "هذا الحساب معطل حالياً. يرجى مراجعة إدارة المدرسة.",
        selectLanguage = "اختر اللغة",
        logout = "تسجيل الخروج",
        roleAdmin = "مدير النظام",
        roleTeacher = "أستاذ",
        roleStudent = "طالب",

        navDashboard = "الرئيسية",
        navUsers = "المستخدمون",
        navTimetable = "جدول الحصص",
        navFinance = "المالية",
        navReports = "التقارير",
        navAttendance = "الغياب والحضور",
        navResources = "المكتبة التعليمية",
        navHomework = "الواجبات",
        navGrades = "كشف النقاط",
        navChat = "المحادثات",
        navAnnouncements = "الإعلانات",
        navSettings = "الإعدادات",
        navGroups = "الأقسام والمواد",

        usersTitle = "إدارة الطلاب والأساتذة",
        studentsTab = "الطلاب",
        teachersTab = "الأساتذة",
        addUser = "إضافة مستخدم جديد",
        addStudent = "إضافة طالب",
        addTeacher = "إضافة أستاذ",
        fullName = "الاسم واللقب",
        phone = "رقم الهاتف",
        autoGeneratePassword = "توليد كلمة سر تلقائية",
        credentialsTitle = "بيانات الدخول للحساب",
        credentialsDesc = "يرجى نسخ هذه البيانات ومشاركتها مع المستخدم الآن. لن يتم عرض كلمة المرور مرة أخرى لدواعي الأمان.",
        copyCredentials = "نسخ بيانات الدخول",
        credentialsCopied = "تم نسخ بيانات الدخول إلى الحافظة",
        editUser = "تعديل الحساب",
        deleteUser = "حذف الحساب",
        disableUser = "تعطيل الحساب",
        enableUser = "تفعيل الحساب",
        confirmDelete = "هل أنت متأكد من رغبتك في حذف هذا الحساب نهائياً؟",
        teacherPermissions = "صلاحيات الأستاذ",
        permPublishResources = "نشر الموارد التعليمية",
        permEditGrades = "إدخال وتعديل النقاط",
        permSendAnnouncements = "إرسال الإعلانات العامة",
        statusActive = "نشط",
        statusDisabled = "معطل",
        searchPlaceholder = "بحث بالاسم أو اسم المستخدم...",

        groupsTitle = "الأقسام والمستويات",
        subjectsTitle = "المواد الدراسية",
        roomsTitle = "القاعات",
        addGroup = "إضافة قسم",
        addSubject = "إضافة مادة",
        addRoom = "إضافة قاعة",
        groupName = "اسم القسم / الفوج",
        subjectName = "اسم المادة",
        teacherName = "اسم الأستاذ",
        roomName = "اسم أو رقم القاعة",
        manualEntry = "كتابة يدوية",
        selectFromList = "اختيار من القائمة",
        level = "المستوى الدراسي",
        timetableTitle = "منشئ جدول الحصص الأسبوعي",
        addSlot = "إضافة حصة دراسية",
        dayOfWeek = "اليوم",
        startTime = "وقت البداية",
        endTime = "وقت النهاية",
        conflictDetected = "تنبيه: تم رصد تعارض في جدول الحصص!",
        conflictRoom = "تعارض: القاعة محجوزة لحصة أخرى في نفس التوقيت!",
        conflictTeacher = "تعارض: الأستاذ مرتبط بحصة أخرى في نفس التوقيت!",
        noConflict = "لا توجد أي تعارضات",
        weeklySchedule = "الجدول الأسبوعي",
        nextClassReminder = "الحصة القادمة قريباً",
        noScheduleToday = "لا توجد حصص مبرمجة اليوم",

        monday = "الإثنين",
        tuesday = "الثلاثاء",
        wednesday = "الأربعاء",
        thursday = "الخميس",
        friday = "الجمعة",
        saturday = "السبت",
        sunday = "الأحد",

        attendanceTitle = "تسجيل الغياب والحضور",
        markAttendance = "أخذ الحضور للحصة",
        present = "حاضر",
        absent = "غائب",
        late = "متأخر",
        attendanceSaved = "تم حفظ قائمة الحضور بنجاح",
        attendanceRate = "نسبة الحضور",
        myAttendanceRecord = "سجل الحضور والغياب الخاص بي",
        totalSessions = "إجمالي الحصص",

        resourcesTitle = "المكتبة والموارد التعليمية",
        addResource = "إضافة مورد تعليمي",
        resourceTitle = "عنوان المورد",
        resourceType = "نوع المورد",
        typeSummary = "ملخص درس",
        typeExercise = "سلسلة تمارين",
        typePastExam = "امتحان سابق مع الحل",
        fileOrUrl = "رابط الملف أو المورد",
        downloadOrOpen = "تحميل / فتح المورد",

        homeworkTitle = "الواجبات المنزلية",
        createHomework = "إنشاء واجب جديد",
        deadline = "آخر أجل للتسليم",
        submissions = "تسليمات الطلاب",
        submitHomework = "تسليم الواجب",
        yourSubmission = "إجابتك / عملك",
        gradeSubmission = "تقييم التسليم",
        score = "العلامة",
        teacherComment = "ملاحظة الأستاذ",
        submittedStatus = "تم التسليم",
        notSubmittedStatus = "لم يتم التسليم بعد",

        gradesTitle = "النقاط والتقييمات",
        addGrade = "رصد نقطة جديدة",
        gradeType = "نوع التقييم",
        typeExam = "امتحان",
        typeQuiz = "فرض / اختبار سريع",
        typeHomeworkGrade = "واجب منزلي",
        gradeValue = "النقطة",
        overallAverage = "المعدل العام",
        progressChart = "مخطط التطور عبر الزمن",

        financeTitle = "المالية والاشتراكات الشهرية",
        monthlyFees = "المستحقات الشهرية",
        paymentStatus = "حالة الدفع",
        statusPaid = "مدفوع",
        statusPending = "قيد الانتظار",
        statusOverdue = "متأخر عن الدفع",
        totalCollected = "إجمالي المبالغ المحصلة",
        totalOverdue = "إجمالي المبالغ المتأخرة",
        recordPayment = "تسجيل دفعة جديدة",
        amount = "المبلغ (د.ج)",
        paymentDate = "تاريخ الدفع",

        reportsTitle = "التقارير الشهرية والسنوية",
        attendanceReport = "تقرير الحضور والغياب",
        gradesReport = "تقرير النتائج والنقاط",
        financeReport = "التقرير المالي",
        exportPdf = "تصدير بتنسيق PDF",
        exportExcel = "تصدير بتنسيق Excel",
        reportExported = "تم إنشاء التقرير بنجاح",

        announcementsTitle = "الإعلانات الرسمية",
        createAnnouncement = "نشر إعلان جديد",
        announcementTitle = "عنوان الإعلان",
        announcementBody = "نص الإعلان الرسمي",
        audienceAll = "الجميع (الكل)",
        audienceTeachers = "الأساتذة فقط",
        audienceStudents = "الطلاب فقط",
        unread = "جديد وغير مقروء",

        chatTitle = "المحادثات والتواصل",
        privateTab = "محادثات فردية",
        groupsTab = "مجموعات الدردشة",
        qaTab = "فضاء الأسئلة والأجوبة",
        newGroupChat = "إنشاء مجموعة دردشة جديدة",
        recordVoice = "تسجيل رسالة صوتية",
        recording = "جارٍ التسجيل الصوتي...",
        stopAndSend = "إيقاف وإرسال التسجيل",
        playAudio = "تشغيل الصوت",
        sendImage = "إرسال صورة",
        typeMessage = "اكتب رسالتك هنا...",
        askQuestion = "طرح سؤال دراسي جديد",
        answerQuestion = "كتابة إجابة",
        replies = "الإجابات",
        moderationNotice = "وضع مراقبة المحادثات من قبل الإدارة",
        deleteMessage = "حذف الرسالة المخالفة",

        save = "حفظ",
        cancel = "إلغاء",
        delete = "حذف",
        edit = "تعديل",
        confirm = "تأكيد",
        close = "إغلاق",
        copy = "نسخ",
        noDataYet = "لا توجد بيانات مسجلة حتى الآن",
        loading = "جارٍ التحميل...",
        success = "تمت العملية بنجاح",
        error = "حدث خطأ. يرجى المحاولة مرة أخرى",
        settingsTitle = "الإعدادات العامة",
        firebaseStatus = "حالة الاتصال بـ Firebase",
        connected = "متصل مباشرة بالسحابة",
        disconnected = "في انتظار الإعداد أو الربط",
        setupInstructions = "دليل ربط مشروع Firebase",
        securityRulesTitle = "قواعد حماية Firestore والتخزين",
        capacitorStepsTitle = "خطوات التحويل لتطبيق APK عبر Capacitor",
        initializeAdminButton = "تهيئة حساب الإدارة (admin/admin)",
        adminInitializedSuccess = "تم إعداد حساب الإدارة admin بنجاح!",

        secureAccountTitle = "تأمين حساب المشرف",
        secureAccountSubtitle = "يجب تغيير كلمة المرور وتعيين بريد استرداد رسمي لحماية الحساب من القفل الدائم.",
        newPassword = "كلمة المرور الجديدة",
        confirmPassword = "تأكيد كلمة المرور",
        recoveryEmail = "بريد الاسترداد الإلكتروني (لإعادة التعيين)",
        changeUsernameOptional = "تغيير اسم المستخدم (اختياري، الافتراضي: admin)",
        passwordCannotBeAdmin = "لا يمكن أن تكون كلمة المرور 'admin' مرة أخرى",
        passwordsDoNotMatch = "كلمتا المرور غير متطابقتين",
        passwordTooShort = "يجب ألا تقل كلمة المرور عن 6 أحرف",
        invalidEmail = "يرجى إدخال عنوان بريد إلكتروني صحيح",
        saveAndContinue = "تأمين الحساب والمتابعة",
        forgotPassword = "نسيت كلمة المرور؟ (للمشرفين)",
        forgotPasswordTitle = "استعادة كلمة المرور للمشرفين",
        forgotPasswordDesc = "أدخل اسم المستخدم أو بريد الاسترداد لتلقي رابط إعادة تعيين كلمة المرور رسمياً من Firebase",
        sendResetLink = "إرسال رابط الاسترداد",
        resetLinkSent = "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريد الاسترداد بنجاح!",
        manageAdmins = "إدارة المشرفين",
        adminsTab = "المشرفون",
        addAdmin = "إضافة مشرف جديد",
        primaryAdmin = "المشرف الأساسي",
        you = "حسابك الحالي",
        cannotDeletePrimaryAdmin = "لا يمكن حذف أو تعطيل المشرف الأساسي للمنظومة لضمان عدم القفل النهائي.",
        changePassword = "تغيير كلمة المرور",
        oldPassword = "كلمة المرور الحالية",
        passwordChangedSuccess = "تم تحديث كلمة المرور بنجاح!"
    )

    val English = AppStrings(
        appName = "science.est.center",
        welcomeTitle = "Welcome to science.est.center",
        welcomeSubtitle = "Integrated Private School Management & Student Support",
        username = "Username",
        password = "Password",
        rememberMe = "Remember me",
        login = "Sign In",
        loggingIn = "Signing in...",
        loginError = "Sign in failed. Check your username and password.",
        invalidCredentials = "Invalid username or password",
        accountDisabled = "This account is currently disabled. Please contact school administration.",
        selectLanguage = "Select Language",
        logout = "Sign Out",
        roleAdmin = "Administrator",
        roleTeacher = "Teacher",
        roleStudent = "Student",

        navDashboard = "Dashboard",
        navUsers = "Users",
        navTimetable = "Timetable",
        navFinance = "Finance",
        navReports = "Reports",
        navAttendance = "Attendance",
        navResources = "Resources",
        navHomework = "Homework",
        navGrades = "Grades",
        navChat = "Messages",
        navAnnouncements = "Announcements",
        navSettings = "Settings",
        navGroups = "Classes & Subjects",

        usersTitle = "User Management",
        studentsTab = "Students",
        teachersTab = "Teachers",
        addUser = "Add New User",
        addStudent = "Add Student",
        addTeacher = "Add Teacher",
        fullName = "Full Name",
        phone = "Phone Number",
        autoGeneratePassword = "Auto-Generate Password",
        credentialsTitle = "Login Credentials",
        credentialsDesc = "Please copy and share these credentials now. For security, passwords will not be displayed again.",
        copyCredentials = "Copy Credentials",
        credentialsCopied = "Credentials copied to clipboard",
        editUser = "Edit Account",
        deleteUser = "Delete Account",
        disableUser = "Disable Account",
        enableUser = "Enable Account",
        confirmDelete = "Are you sure you want to permanently delete this account?",
        teacherPermissions = "Teacher Permissions",
        permPublishResources = "Publish Learning Resources",
        permEditGrades = "Edit Grades",
        permSendAnnouncements = "Send Announcements",
        statusActive = "Active",
        statusDisabled = "Disabled",
        searchPlaceholder = "Search by name or username...",

        groupsTitle = "Classes & Groups",
        subjectsTitle = "Subjects",
        roomsTitle = "Rooms",
        addGroup = "Add Class",
        addSubject = "Add Subject",
        addRoom = "Add Room",
        groupName = "Class / Group Name",
        subjectName = "Subject Name",
        teacherName = "Teacher Name",
        roomName = "Room Name / Number",
        manualEntry = "Manual Entry",
        selectFromList = "Select from List",
        level = "Academic Level",
        timetableTitle = "Weekly Timetable Builder",
        addSlot = "Add Class Slot",
        dayOfWeek = "Day",
        startTime = "Start Time",
        endTime = "End Time",
        conflictDetected = "Warning: Timetable conflict detected!",
        conflictRoom = "Conflict: Room is already booked for another session at this time!",
        conflictTeacher = "Conflict: Teacher already has another session at this time!",
        noConflict = "No conflicts detected",
        weeklySchedule = "Weekly Schedule",
        nextClassReminder = "Upcoming class reminder",
        noScheduleToday = "No classes scheduled for today",

        monday = "Monday",
        tuesday = "Tuesday",
        wednesday = "Wednesday",
        thursday = "Thursday",
        friday = "Friday",
        saturday = "Saturday",
        sunday = "Sunday",

        attendanceTitle = "Attendance Tracking",
        markAttendance = "Mark Session Attendance",
        present = "Present",
        absent = "Absent",
        late = "Late",
        attendanceSaved = "Attendance successfully saved",
        attendanceRate = "Attendance Rate",
        myAttendanceRecord = "My Attendance History",
        totalSessions = "Total Sessions",

        resourcesTitle = "Learning Resources",
        addResource = "Add Resource",
        resourceTitle = "Resource Title",
        resourceType = "Resource Type",
        typeSummary = "Lesson Summary",
        typeExercise = "Exercise Sheet",
        typePastExam = "Past Exam with Solution",
        fileOrUrl = "Resource File / Link",
        downloadOrOpen = "Download / Open Resource",

        homeworkTitle = "Homework & Assignments",
        createHomework = "Create Assignment",
        deadline = "Deadline",
        submissions = "Student Submissions",
        submitHomework = "Submit Homework",
        yourSubmission = "Your Submission",
        gradeSubmission = "Grade Submission",
        score = "Grade / Score",
        teacherComment = "Teacher Feedback",
        submittedStatus = "Submitted",
        notSubmittedStatus = "Not submitted yet",

        gradesTitle = "Student Grades",
        addGrade = "Record Grade",
        gradeType = "Grade Type",
        typeExam = "Exam",
        typeQuiz = "Quiz",
        typeHomeworkGrade = "Homework",
        gradeValue = "Grade Value",
        overallAverage = "Overall Average",
        progressChart = "Progress Over Time",

        financeTitle = "School Finance & Fees",
        monthlyFees = "Monthly Fees",
        paymentStatus = "Payment Status",
        statusPaid = "Paid",
        statusPending = "Pending",
        statusOverdue = "Overdue",
        totalCollected = "Total Collected",
        totalOverdue = "Total Overdue",
        recordPayment = "Record Payment",
        amount = "Amount",
        paymentDate = "Payment Date",

        reportsTitle = "Monthly Reports",
        attendanceReport = "Attendance Report",
        gradesReport = "Academic Grades Report",
        financeReport = "Financial Summary Report",
        exportPdf = "Export as PDF",
        exportExcel = "Export as Excel",
        reportExported = "Report generated successfully",

        announcementsTitle = "Official Announcements",
        createAnnouncement = "Post Announcement",
        announcementTitle = "Announcement Title",
        announcementBody = "Announcement Content",
        audienceAll = "Everyone",
        audienceTeachers = "Teachers Only",
        audienceStudents = "Students Only",
        unread = "Unread",

        chatTitle = "Messages & Discussions",
        privateTab = "Direct Messages",
        groupsTab = "Chat Groups",
        qaTab = "Subject Q&A",
        newGroupChat = "New Chat Group",
        recordVoice = "Record Voice Note",
        recording = "Recording voice...",
        stopAndSend = "Stop & Send Audio",
        playAudio = "Play Audio",
        sendImage = "Send Photo",
        typeMessage = "Type a message...",
        askQuestion = "Ask a Question",
        answerQuestion = "Post Answer",
        replies = "Replies",
        moderationNotice = "Admin Moderation View Active",
        deleteMessage = "Delete Violating Message",

        save = "Save",
        cancel = "Cancel",
        delete = "Delete",
        edit = "Edit",
        confirm = "Confirm",
        close = "Close",
        copy = "Copy",
        noDataYet = "No data yet",
        loading = "Loading...",
        success = "Operation completed successfully",
        error = "An error occurred. Please try again.",
        settingsTitle = "Settings",
        firebaseStatus = "Firebase Status",
        connected = "Live Cloud Connected",
        disconnected = "Awaiting Setup",
        setupInstructions = "Firebase Connection Guide",
        securityRulesTitle = "Firestore & Storage Security Rules",
        capacitorStepsTitle = "Capacitor APK Conversion Steps",
        initializeAdminButton = "Initialize Admin Account (admin/admin)",
        adminInitializedSuccess = "Admin account initialized successfully!",

        secureAccountTitle = "Secure Your Admin Account",
        secureAccountSubtitle = "You must change your password and provide a real recovery email address to protect this account from permanent lockout.",
        newPassword = "New Password",
        confirmPassword = "Confirm New Password",
        recoveryEmail = "Recovery Email Address",
        changeUsernameOptional = "Change Username (optional, default: admin)",
        passwordCannotBeAdmin = "Password cannot be 'admin' again",
        passwordsDoNotMatch = "Passwords do not match",
        passwordTooShort = "Password must be at least 6 characters",
        invalidEmail = "Please enter a valid email address",
        saveAndContinue = "Secure Account & Continue",
        forgotPassword = "Forgot Password? (Admins)",
        forgotPasswordTitle = "Admin Password Recovery",
        forgotPasswordDesc = "Enter your admin username or registered recovery email to receive a password reset link via Firebase",
        sendResetLink = "Send Reset Link",
        resetLinkSent = "Password reset link sent to your recovery email successfully!",
        manageAdmins = "Manage Admins",
        adminsTab = "Admins",
        addAdmin = "Add New Admin",
        primaryAdmin = "Primary Admin",
        you = "You (current session)",
        cannotDeletePrimaryAdmin = "The primary admin cannot be disabled or deleted to prevent total lockout.",
        changePassword = "Change Password",
        oldPassword = "Current Password",
        passwordChangedSuccess = "Password updated successfully!"
    )

    val French = AppStrings(
        appName = "science.est.center",
        welcomeTitle = "Bienvenue sur science.est.center",
        welcomeSubtitle = "Gestion d'école privée et soutien scolaire intégré",
        username = "Nom d'utilisateur",
        password = "Mot de passe",
        rememberMe = "Se souvenir de moi",
        login = "Connexion",
        loggingIn = "Connexion en cours...",
        loginError = "Échec de connexion. Vérifiez le nom d'utilisateur et le mot de passe.",
        invalidCredentials = "Nom d'utilisateur ou mot de passe incorrect",
        accountDisabled = "Ce compte est actuellement désactivé. Veuillez contacter l'administration.",
        selectLanguage = "Choisir la langue",
        logout = "Déconnexion",
        roleAdmin = "Administrateur",
        roleTeacher = "Enseignant",
        roleStudent = "Élève",

        navDashboard = "Tableau de bord",
        navUsers = "Utilisateurs",
        navTimetable = "Emploi du temps",
        navFinance = "Finances",
        navReports = "Rapports",
        navAttendance = "Présences",
        navResources = "Ressources",
        navHomework = "Devoirs",
        navGrades = "Notes",
        navChat = "Messagerie",
        navAnnouncements = "Annonces",
        navSettings = "Paramètres",
        navGroups = "Classes & Matières",

        usersTitle = "Gestion des utilisateurs",
        studentsTab = "Élèves",
        teachersTab = "Enseignants",
        addUser = "Ajouter un utilisateur",
        addStudent = "Ajouter un élève",
        addTeacher = "Ajouter un enseignant",
        fullName = "Nom complet",
        phone = "Téléphone",
        autoGeneratePassword = "Générer un mot de passe",
        credentialsTitle = "Identifiants de connexion",
        credentialsDesc = "Veuillez copier et transmettre ces identifiants dès maintenant. Le mot de passe ne sera plus affiché.",
        copyCredentials = "Copier les identifiants",
        credentialsCopied = "Identifiants copiés dans le presse-papiers",
        editUser = "Modifier le compte",
        deleteUser = "Supprimer le compte",
        disableUser = "Désactiver le compte",
        enableUser = "Activer le compte",
        confirmDelete = "Voulez-vous vraiment supprimer définitivement ce compte ?",
        teacherPermissions = "Permissions de l'enseignant",
        permPublishResources = "Publier des ressources",
        permEditGrades = "Modifier les notes",
        permSendAnnouncements = "Envoyer des annonces",
        statusActive = "Actif",
        statusDisabled = "Désactivé",
        searchPlaceholder = "Rechercher par nom ou identifiant...",

        groupsTitle = "Classes et Groupes",
        subjectsTitle = "Matières",
        roomsTitle = "Salles de cours",
        addGroup = "Ajouter une classe",
        addSubject = "Ajouter une matière",
        addRoom = "Ajouter une salle",
        groupName = "Nom de la classe",
        subjectName = "Nom de la matière",
        teacherName = "Nom de l'enseignant",
        roomName = "Numéro de salle",
        manualEntry = "Saisie manuelle",
        selectFromList = "Choisir dans la liste",
        level = "Niveau scolaire",
        timetableTitle = "Générateur d'emploi du temps",
        addSlot = "Ajouter un créneau",
        dayOfWeek = "Jour",
        startTime = "Heure de début",
        endTime = "Heure de fin",
        conflictDetected = "Alerte : Conflit d'horaire détecté !",
        conflictRoom = "Conflit : La salle est déjà occupée sur ce créneau !",
        conflictTeacher = "Conflit : L'enseignant a déjà un cours sur ce créneau !",
        noConflict = "Aucun conflit détecté",
        weeklySchedule = "Emploi du temps hebdomadaire",
        nextClassReminder = "Rappel du prochain cours",
        noScheduleToday = "Aucun cours prévu aujourd'hui",

        monday = "Lundi",
        tuesday = "Mardi",
        wednesday = "Mercredi",
        thursday = "Jeudi",
        friday = "Vendredi",
        saturday = "Samedi",
        sunday = "Dimanche",

        attendanceTitle = "Feuille de présence",
        markAttendance = "Faire l'appel",
        present = "Présent",
        absent = "Absent",
        late = "En retard",
        attendanceSaved = "Présences enregistrées avec succès",
        attendanceRate = "Taux de présence",
        myAttendanceRecord = "Mon historique de présence",
        totalSessions = "Total des séances",

        resourcesTitle = "Ressources pédagogiques",
        addResource = "Ajouter une ressource",
        resourceTitle = "Titre de la ressource",
        resourceType = "Type de ressource",
        typeSummary = "Fiche de cours / Résumé",
        typeExercise = "Série d'exercices",
        typePastExam = "Ancien examen avec corrigé",
        fileOrUrl = "Fichier ou lien web",
        downloadOrOpen = "Télécharger / Consulter",

        homeworkTitle = "Devoirs et travaux",
        createHomework = "Créer un devoir",
        deadline = "Date limite de remise",
        submissions = "Travaux rendus",
        submitHomework = "Rendre le devoir",
        yourSubmission = "Votre rendu",
        gradeSubmission = "Évaluer le rendu",
        score = "Note / Barème",
        teacherComment = "Commentaire de l'enseignant",
        submittedStatus = "Rendu",
        notSubmittedStatus = "Non rendu",

        gradesTitle = "Notes et évaluations",
        addGrade = "Saisir une note",
        gradeType = "Type d'évaluation",
        typeExam = "Examen",
        typeQuiz = "Interrogation",
        typeHomeworkGrade = "Devoir maison",
        gradeValue = "Note",
        overallAverage = "Moyenne générale",
        progressChart = "Courbe de progression",

        financeTitle = "Finances & Frais de scolarité",
        monthlyFees = "Frais mensuels",
        paymentStatus = "Statut de paiement",
        statusPaid = "Payé",
        statusPending = "En attente",
        statusOverdue = "En retard",
        totalCollected = "Total encaissé",
        totalOverdue = "Total impayé",
        recordPayment = "Enregistrer un paiement",
        amount = "Montant",
        paymentDate = "Date du versement",

        reportsTitle = "Rapports d'activité",
        attendanceReport = "Rapport d'assiduité",
        gradesReport = "Relevé des notes",
        financeReport = "Bilan financier",
        exportPdf = "Exporter en PDF",
        exportExcel = "Exporter en Excel",
        reportExported = "Rapport généré avec succès",

        announcementsTitle = "Annonces officielles",
        createAnnouncement = "Publier une annonce",
        announcementTitle = "Titre de l'annonce",
        announcementBody = "Contenu de l'annonce",
        audienceAll = "Tout le monde",
        audienceTeachers = "Enseignants uniquement",
        audienceStudents = "Élèves uniquement",
        unread = "Non lu",

        chatTitle = "Messagerie & Échanges",
        privateTab = "Messages privés",
        groupsTab = "Groupes de discussion",
        qaTab = "Espace Questions / Réponses",
        newGroupChat = "Créer un groupe de discussion",
        recordVoice = "Enregistrer un message vocal",
        recording = "Enregistrement en cours...",
        stopAndSend = "Arrêter et envoyer",
        playAudio = "Écouter l'audio",
        sendImage = "Envoyer une photo",
        typeMessage = "Écrivez votre message...",
        askQuestion = "Poser une question",
        answerQuestion = "Répondre",
        replies = "Réponses",
        moderationNotice = "Modération active par l'administration",
        deleteMessage = "Supprimer le message",

        save = "Enregistrer",
        cancel = "Annuler",
        delete = "Supprimer",
        edit = "Modifier",
        confirm = "Confirmer",
        close = "Fermer",
        copy = "Copier",
        noDataYet = "Aucune donnée enregistrée pour le moment",
        loading = "Chargement en cours...",
        success = "Opération réussie",
        error = "Une erreur est survenue. Veuillez réessayer.",
        settingsTitle = "Paramètres",
        firebaseStatus = "État de la connexion Firebase",
        connected = "Connecté au Cloud Firebase",
        disconnected = "En attente de configuration",
        setupInstructions = "Guide de connexion Firebase",
        securityRulesTitle = "Règles de sécurité Firestore et Storage",
        capacitorStepsTitle = "Étapes de conversion Capacitor APK",
        initializeAdminButton = "Initialiser le compte administrateur (admin/admin)",
        adminInitializedSuccess = "Compte administrateur initialisé avec succès !",

        secureAccountTitle = "Sécuriser votre compte administrateur",
        secureAccountSubtitle = "Vous devez changer votre mot de passe et définir une adresse e-mail de récupération pour éviter tout blocage permanent.",
        newPassword = "Nouveau mot de passe",
        confirmPassword = "Confirmer le nouveau mot de passe",
        recoveryEmail = "E-mail de récupération",
        changeUsernameOptional = "Changer le nom d'utilisateur (facultatif, par défaut : admin)",
        passwordCannotBeAdmin = "Le mot de passe ne peut pas être 'admin' à nouveau",
        passwordsDoNotMatch = "Les mots de passe ne correspondent pas",
        passwordTooShort = "Le mot de passe doit comporter au moins 6 caractères",
        invalidEmail = "Veuillez saisir une adresse e-mail valide",
        saveAndContinue = "Sécuriser le compte et continuer",
        forgotPassword = "Mot de passe oublié ? (Admins)",
        forgotPasswordTitle = "Récupération du mot de passe",
        forgotPasswordDesc = "Entrez votre nom d'utilisateur ou e-mail de récupération pour recevoir un lien de réinitialisation",
        sendResetLink = "Envoyer le lien de réinitialisation",
        resetLinkSent = "Lien de réinitialisation envoyé avec succès à votre e-mail de récupération !",
        manageAdmins = "Gérer les administrateurs",
        adminsTab = "Admins",
        addAdmin = "Ajouter un administrateur",
        primaryAdmin = "Administrateur principal",
        you = "Vous (session actuelle)",
        cannotDeletePrimaryAdmin = "L'administrateur principal ne peut être ni supprimé ni désactivé.",
        changePassword = "Changer le mot de passe",
        oldPassword = "Mot de passe actuel",
        passwordChangedSuccess = "Mot de passe mis à jour avec succès !"
    )

    fun get(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ARABIC -> Arabic
            AppLanguage.ENGLISH -> English
            AppLanguage.FRENCH -> French
        }
    }
}
